# permissions for end users to edit scopes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scope-editor-role
rules:
- apiGroups:
  - cache.ghostbaby.io
  resources:
  - scopes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.ghostbaby.io
  resources:
  - scopes/status
  verbs:
  - get
