# permissions for end users to edit workloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workload-editor-role
rules:
- apiGroups:
  - zk.cache.ghostbaby.io
  resources:
  - workloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zk.cache.ghostbaby.io
  resources:
  - workloads/status
  verbs:
  - get
