name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    name: DockerLint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: lint
        uses: brpaz/hadolint-action@master

  # Golang tests
  go-lint:
    runs-on: ubuntu-latest
    name: GoLint
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
        with:
          golangci_lint_version: 1.22.2

  # Dockerfile tests
  docker-build-test:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - uses: actions/checkout@v2
      - name: install kubebuilder
        run: |
          curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_linux_amd64.tar.gz | tar -xz -C /tmp/
          sudo mv /tmp/kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder
      - run: make test docker-build
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ghostbaby/zookeeper-operator
          tag_with_ref: true